export default {
  kind: "customsearch#search",
  url: {
    type: "application/json",
    template:
      "https://www.googleapis.com/customsearch/v1?q={searchTerms}&num={count?}&start={startIndex?}&lr={language?}&safe={safe?}&cx={cx?}&sort={sort?}&filter={filter?}&gl={gl?}&cr={cr?}&googlehost={googleHost?}&c2coff={disableCnTwTranslation?}&hq={hq?}&hl={hl?}&siteSearch={siteSearch?}&siteSearchFilter={siteSearchFilter?}&exactTerms={exactTerms?}&excludeTerms={excludeTerms?}&linkSite={linkSite?}&orTerms={orTerms?}&relatedSite={relatedSite?}&dateRestrict={dateRestrict?}&lowRange={lowRange?}&highRange={highRange?}&searchType={searchType}&fileType={fileType?}&rights={rights?}&imgSize={imgSize?}&imgType={imgType?}&imgColorType={imgColorType?}&imgDominantColor={imgDominantColor?}&alt=json",
  },
  queries: {
    request: [
      {
        title: "Google Custom Search - tailwind",
        totalResults: "75800000",
        searchTerms: "tailwind",
        count: 10,
        startIndex: 1,
        inputEncoding: "utf8",
        outputEncoding: "utf8",
        safe: "off",
        cx: "084b81a83eaae14be",
        searchType: "image",
      },
    ],
    nextPage: [
      {
        title: "Google Custom Search - tailwind",
        totalResults: "75800000",
        searchTerms: "tailwind",
        count: 10,
        startIndex: 11,
        inputEncoding: "utf8",
        outputEncoding: "utf8",
        safe: "off",
        cx: "084b81a83eaae14be",
        searchType: "image",
      },
    ],
  },
  context: {
    title: "searchEngine",
  },
  searchInformation: {
    searchTime: 0.143122,
    formattedSearchTime: "0.14",
    totalResults: "75800000",
    formattedTotalResults: "75,800,000",
  },
  items: [
    {
      kind: "customsearch#result",
      title: "Tailwind Capital | LinkedIn",
      htmlTitle: "<b>Tailwind</b> Capital | LinkedIn",
      link: "https://media-exp1.licdn.com/dms/image/C4E0BAQERLvoHK_rN5A/company-logo_200_200/0/1637247649960?e=2147483647&v=beta&t=KOBLtvGkx66EBelZDoFXx9Vq1KJLmBiqHZ81AETIOBQ",
      displayLink: "www.linkedin.com",
      snippet: "Tailwind Capital | LinkedIn",
      htmlSnippet: "<b>Tailwind</b> Capital | LinkedIn",
      mime: "image/",
      fileFormat: "image/",
      image: {
        contextLink: "https://www.linkedin.com/company/tailwind-capital",
        height: 200,
        width: 200,
        byteSize: 5161,
        thumbnailLink:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS49JaOf5_2aI1zQ-DG3waTFK9xA-clWpMhKiA_ZIgXaDPdE7HG-hDuWA&s",
        thumbnailHeight: 104,
        thumbnailWidth: 104,
      },
    },
    {
      kind: "customsearch#result",
      title: "Leadership :: Tailwind Two Acquisition Corp. (TWNT)",
      htmlTitle: "Leadership :: <b>Tailwind</b> Two Acquisition Corp. (TWNT)",
      link: "https://d1io3yog0oux5.cloudfront.net/_3c17c94a5872295d109a6ef2055d7d28/twnt/logo.png",
      displayLink: "twnt.tailwindacquisition.com",
      snippet: "Leadership :: Tailwind Two Acquisition Corp. (TWNT)",
      htmlSnippet: "Leadership :: <b>Tailwind</b> Two Acquisition Corp. (TWNT)",
      mime: "image/png",
      fileFormat: "image/png",
      image: {
        contextLink: "https://twnt.tailwindacquisition.com/leadership",
        height: 469,
        width: 600,
        byteSize: 35990,
        thumbnailLink:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSr7LH_Snpu91_M7ZlEWnRJnNZYPyMd0pVtQ70yKiv-2sWOkhbteJeXHg&s",
        thumbnailHeight: 106,
        thumbnailWidth: 135,
      },
    },
    {
      kind: "customsearch#result",
      title: "Nike Air Max Tailwind 4 Black White - AQ2567-004",
      htmlTitle: "Nike Air Max <b>Tailwind</b> 4 Black White - AQ2567-004",
      link: "https://images.stockx.com/images/Nike-Air-Max-Tailwind-4-Black-White-Product.jpg?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&q=90&dpr=2&trim=color&updated_at=1607047776",
      displayLink: "stockx.com",
      snippet: "Nike Air Max Tailwind 4 Black White - AQ2567-004",
      htmlSnippet: "Nike Air Max <b>Tailwind</b> 4 Black White - AQ2567-004",
      mime: "image/jpeg",
      fileFormat: "image/jpeg",
      image: {
        contextLink: "https://stockx.com/nike-air-max-tailwind-4-black-white",
        height: 1000,
        width: 1400,
        byteSize: 209176,
        thumbnailLink:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT03Cgnyedj3z9oH2-ktzTKleLmPAP7KgG-y56-kkfDkDGVtKfcB0t1fyk&s",
        thumbnailHeight: 107,
        thumbnailWidth: 150,
      },
    },
    {
      kind: "customsearch#result",
      title: "11 Benefits of Tailwind CSS | Laravel News",
      htmlTitle: "11 Benefits of <b>Tailwind</b> CSS | Laravel News",
      link: "https://laravelnews.imgix.net/images/tailwindcss.png?ixlib=php-3.3.1",
      displayLink: "laravel-news.com",
      snippet: "11 Benefits of Tailwind CSS | Laravel News",
      htmlSnippet: "11 Benefits of <b>Tailwind</b> CSS | Laravel News",
      mime: "image/png",
      fileFormat: "image/png",
      image: {
        contextLink: "https://laravel-news.com/11-benefits-of-tailwind-css",
        height: 1100,
        width: 2200,
        byteSize: 154502,
        thumbnailLink:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0rgcI4wQoxw6olZSjzgQfpf6AKWBLn7Z8LdJkjiSwKey509NPL5IBx30&s",
        thumbnailHeight: 75,
        thumbnailWidth: 150,
      },
    },
    {
      kind: "customsearch#result",
      title: "Tailwind Acquisition Corp.",
      htmlTitle: "<b>Tailwind</b> Acquisition Corp.",
      link: "https://d1io3yog0oux5.cloudfront.net/tailwindacquisition/files/theme/images/logo-600px-white.png",
      displayLink: "www.tailwindacquisition.com",
      snippet: "Tailwind Acquisition Corp.",
      htmlSnippet: "<b>Tailwind</b> Acquisition Corp.",
      mime: "image/png",
      fileFormat: "image/png",
      image: {
        contextLink: "https://www.tailwindacquisition.com/",
        height: 342,
        width: 600,
        byteSize: 42834,
        thumbnailLink:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSFla0FZtwq3X29TcO9cxa9qZeyo42H1QU_u0mc_b0KVmxNcPWA6QGnoic&s",
        thumbnailHeight: 77,
        thumbnailWidth: 135,
      },
    },
    {
      kind: "customsearch#result",
      title: "More OG Nike Air Max Tailwind 4 Colourways Surface - Sneaker Freaker",
      htmlTitle: "More OG Nike Air Max <b>Tailwind</b> 4 Colourways Surface - Sneaker Freaker",
      link: "https://cdn.sanity.io/images/c1chvb1i/production/eb41a7b61872c0ef2038fb3ff6f9ba294c4c047b-700x468.jpg",
      displayLink: "www.sneakerfreaker.com",
      snippet: "More OG Nike Air Max Tailwind 4 Colourways Surface - Sneaker Freaker",
      htmlSnippet: "More OG Nike Air Max <b>Tailwind</b> 4 Colourways Surface - Sneaker Freaker",
      mime: "image/jpeg",
      fileFormat: "image/jpeg",
      image: {
        contextLink:
          "https://www.sneakerfreaker.com/releases/more-og-nike-air-max-tailwind-4-colourways-surface",
        height: 468,
        width: 700,
        byteSize: 41540,
        thumbnailLink:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRaWK4qofbGEPwKjAc2nZldW9rcKhcsmbCts_8tYqQ9LxbnrSkbGiVQO6U&s",
        thumbnailHeight: 94,
        thumbnailWidth: 140,
      },
    },
    {
      kind: "customsearch#result",
      title: "Tailwind Acquisition Corp.",
      htmlTitle: "<b>Tailwind</b> Acquisition Corp.",
      link: "https://d1io3yog0oux5.cloudfront.net/_8bae197612d19fb37b557f04301ba104/tailwindacquisition/db/1104/9259/social_image_resized.jpg",
      displayLink: "www.tailwindacquisition.com",
      snippet: "Tailwind Acquisition Corp.",
      htmlSnippet: "<b>Tailwind</b> Acquisition Corp.",
      mime: "image/jpeg",
      fileFormat: "image/jpeg",
      image: {
        contextLink: "https://www.tailwindacquisition.com/",
        height: 627,
        width: 1200,
        byteSize: 34514,
        thumbnailLink:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTBt7Af9QI4xvjJlti69E7jedTJ5FeGtQ7MTBfSxkzIh7ZLzg8xiS7uiQ&s",
        thumbnailHeight: 78,
        thumbnailWidth: 150,
      },
    },
    {
      kind: "customsearch#result",
      title: "Amazon.com | Nike Women's Air Max Tailwind IV NRG | Road Running",
      htmlTitle: "Amazon.com | Nike Women&#39;s Air Max <b>Tailwind</b> IV NRG | Road Running",
      link: "https://m.media-amazon.com/images/I/71K1r3RDQ7L._AC_UX395_.jpg",
      displayLink: "www.amazon.com",
      snippet: "Amazon.com | Nike Women's Air Max Tailwind IV NRG | Road Running",
      htmlSnippet: "Amazon.com | Nike Women&#39;s Air Max <b>Tailwind</b> IV NRG | Road Running",
      mime: "image/jpeg",
      fileFormat: "image/jpeg",
      image: {
        contextLink: "https://www.amazon.com/Nike-Womens-Tailwind-Black-White-Black/dp/B084P26KP6",
        height: 240,
        width: 395,
        byteSize: 12688,
        thumbnailLink:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5MtfRPiE6Zoz4EfrgYtuW9dXLKlyc0-ZQSLIn5mPJmog2I2Dd4mqw&s",
        thumbnailHeight: 75,
        thumbnailWidth: 124,
      },
    },
    {
      kind: "customsearch#result",
      title: "Nike Air Max Tailwind 4 Black Gold CT1284-001 | SneakerNews.com",
      htmlTitle: "Nike Air Max <b>Tailwind</b> 4 Black Gold CT1284-001 | SneakerNews.com",
      link: "https://sneakernews.com/wp-content/uploads/2020/07/nike-air-max-tailwind-4-black-metallic-gold-CT1284-001-6.jpg",
      displayLink: "sneakernews.com",
      snippet: "Nike Air Max Tailwind 4 Black Gold CT1284-001 | SneakerNews.com",
      htmlSnippet: "Nike Air Max <b>Tailwind</b> 4 Black Gold CT1284-001 | SneakerNews.com",
      mime: "image/jpeg",
      fileFormat: "image/jpeg",
      image: {
        contextLink:
          "https://sneakernews.com/2020/07/30/nike-air-max-tailwind-4-black-metallic-gold-ct1284-001-release-info/",
        height: 800,
        width: 1140,
        byteSize: 388604,
        thumbnailLink:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMUGVfhnqN9WSt7n5bx8ACdNIYFxytIXdnyBBPG00JCiLvjZvRyTaysQ&s",
        thumbnailHeight: 105,
        thumbnailWidth: 150,
      },
    },
    {
      kind: "customsearch#result",
      title: "Amazon.com | Nike Air Max Tailwind Iv Womens Shoes | Fashion Sneakers",
      htmlTitle: "Amazon.com | Nike Air Max <b>Tailwind</b> Iv Womens Shoes | Fashion Sneakers",
      link: "https://m.media-amazon.com/images/I/71hS9nZIV8L._AC_UY535_.jpg",
      displayLink: "www.amazon.com",
      snippet: "Amazon.com | Nike Air Max Tailwind Iv Womens Shoes | Fashion Sneakers",
      htmlSnippet: "Amazon.com | Nike Air Max <b>Tailwind</b> Iv Womens Shoes | Fashion Sneakers",
      mime: "image/jpeg",
      fileFormat: "image/jpeg",
      image: {
        contextLink: "https://www.amazon.com/Nike-Air-Tailwind-Womens-Shoes/dp/B08MYCKFGJ",
        height: 535,
        width: 1107,
        byteSize: 78687,
        thumbnailLink:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT10GHp348i6ylNN1yq0BI2u4pJtMWJfy6wxO_jDOEk-faQqIZcuU8-fA&s",
        thumbnailHeight: 72,
        thumbnailWidth: 150,
      },
    },
  ],
};
